FROM node:15.14 AS build-stage
COPY . /app
WORKDIR /app
RUN yarn install --production && yarn build

FROM nginx:alpine
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=build-stage /app/build .
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]