FROM node:15.14 AS build-stage
COPY . /app
WORKDIR /app
RUN yarn install --production && yarn build

FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY --from=build-stage /app/build .
COPY nginx.conf /etc/nginx/conf.d
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]